/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrinciplesRouteImport } from './routes/principles'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSimulatorRouteImport } from './routes/_authenticated/simulator'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRetirementRouteImport } from './routes/_authenticated/retirement'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPeerBenchmarkRouteImport } from './routes/_authenticated/peer-benchmark'
import { Route as AuthenticatedNetWorthRouteImport } from './routes/_authenticated/net-worth'
import { Route as AuthenticatedInsuranceRouteImport } from './routes/_authenticated/insurance'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedFinancialHealthRouteImport } from './routes/_authenticated/financial-health'
import { Route as AuthenticatedEmergencyFundRouteImport } from './routes/_authenticated/emergency-fund'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiCoachRouteImport } from './routes/_authenticated/ai-coach'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesRoute = PrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimulatorRoute = AuthenticatedSimulatorRouteImport.update({
  id: '/_authenticated/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRetirementRoute = AuthenticatedRetirementRouteImport.update({
  id: '/_authenticated/retirement',
  path: '/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/_authenticated/recommendations',
    path: '/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPeerBenchmarkRoute =
  AuthenticatedPeerBenchmarkRouteImport.update({
    id: '/_authenticated/peer-benchmark',
    path: '/peer-benchmark',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedNetWorthRoute = AuthenticatedNetWorthRouteImport.update({
  id: '/_authenticated/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInsuranceRoute = AuthenticatedInsuranceRouteImport.update({
  id: '/_authenticated/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/_authenticated/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFinancialHealthRoute =
  AuthenticatedFinancialHealthRouteImport.update({
    id: '/_authenticated/financial-health',
    path: '/financial-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEmergencyFundRoute =
  AuthenticatedEmergencyFundRouteImport.update({
    id: '/_authenticated/emergency-fund',
    path: '/emergency-fund',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiCoachRoute = AuthenticatedAiCoachRouteImport.update({
  id: '/_authenticated/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/knowledge': typeof KnowledgeRoute
  '/principles': typeof PrinciplesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency-fund': typeof AuthenticatedEmergencyFundRoute
  '/financial-health': typeof AuthenticatedFinancialHealthRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/net-worth': typeof AuthenticatedNetWorthRoute
  '/peer-benchmark': typeof AuthenticatedPeerBenchmarkRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/retirement': typeof AuthenticatedRetirementRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/knowledge': typeof KnowledgeRoute
  '/principles': typeof PrinciplesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency-fund': typeof AuthenticatedEmergencyFundRoute
  '/financial-health': typeof AuthenticatedFinancialHealthRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/net-worth': typeof AuthenticatedNetWorthRoute
  '/peer-benchmark': typeof AuthenticatedPeerBenchmarkRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/retirement': typeof AuthenticatedRetirementRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/knowledge': typeof KnowledgeRoute
  '/principles': typeof PrinciplesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ai-coach': typeof AuthenticatedAiCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emergency-fund': typeof AuthenticatedEmergencyFundRoute
  '/_authenticated/financial-health': typeof AuthenticatedFinancialHealthRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRoute
  '/_authenticated/net-worth': typeof AuthenticatedNetWorthRoute
  '/_authenticated/peer-benchmark': typeof AuthenticatedPeerBenchmarkRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/retirement': typeof AuthenticatedRetirementRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/simulator': typeof AuthenticatedSimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/how-it-works'
    | '/knowledge'
    | '/principles'
    | '/sitemap.xml'
    | '/ai-coach'
    | '/dashboard'
    | '/emergency-fund'
    | '/financial-health'
    | '/goals'
    | '/insurance'
    | '/net-worth'
    | '/peer-benchmark'
    | '/profile'
    | '/recommendations'
    | '/retirement'
    | '/settings'
    | '/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/how-it-works'
    | '/knowledge'
    | '/principles'
    | '/sitemap.xml'
    | '/ai-coach'
    | '/dashboard'
    | '/emergency-fund'
    | '/financial-health'
    | '/goals'
    | '/insurance'
    | '/net-worth'
    | '/peer-benchmark'
    | '/profile'
    | '/recommendations'
    | '/retirement'
    | '/settings'
    | '/simulator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/how-it-works'
    | '/knowledge'
    | '/principles'
    | '/sitemap.xml'
    | '/_authenticated/ai-coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/emergency-fund'
    | '/_authenticated/financial-health'
    | '/_authenticated/goals'
    | '/_authenticated/insurance'
    | '/_authenticated/net-worth'
    | '/_authenticated/peer-benchmark'
    | '/_authenticated/profile'
    | '/_authenticated/recommendations'
    | '/_authenticated/retirement'
    | '/_authenticated/settings'
    | '/_authenticated/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HowItWorksRoute: typeof HowItWorksRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PrinciplesRoute: typeof PrinciplesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthenticatedAiCoachRoute: typeof AuthenticatedAiCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmergencyFundRoute: typeof AuthenticatedEmergencyFundRoute
  AuthenticatedFinancialHealthRoute: typeof AuthenticatedFinancialHealthRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedInsuranceRoute: typeof AuthenticatedInsuranceRoute
  AuthenticatedNetWorthRoute: typeof AuthenticatedNetWorthRoute
  AuthenticatedPeerBenchmarkRoute: typeof AuthenticatedPeerBenchmarkRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedRetirementRoute: typeof AuthenticatedRetirementRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSimulatorRoute: typeof AuthenticatedSimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles': {
      id: '/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof PrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulator': {
      id: '/_authenticated/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AuthenticatedSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/retirement': {
      id: '/_authenticated/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof AuthenticatedRetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/peer-benchmark': {
      id: '/_authenticated/peer-benchmark'
      path: '/peer-benchmark'
      fullPath: '/peer-benchmark'
      preLoaderRoute: typeof AuthenticatedPeerBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/net-worth': {
      id: '/_authenticated/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof AuthenticatedNetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/financial-health': {
      id: '/_authenticated/financial-health'
      path: '/financial-health'
      fullPath: '/financial-health'
      preLoaderRoute: typeof AuthenticatedFinancialHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/emergency-fund': {
      id: '/_authenticated/emergency-fund'
      path: '/emergency-fund'
      fullPath: '/emergency-fund'
      preLoaderRoute: typeof AuthenticatedEmergencyFundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-coach': {
      id: '/_authenticated/ai-coach'
      path: '/ai-coach'
      fullPath: '/ai-coach'
      preLoaderRoute: typeof AuthenticatedAiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HowItWorksRoute: HowItWorksRoute,
  KnowledgeRoute: KnowledgeRoute,
  PrinciplesRoute: PrinciplesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthenticatedAiCoachRoute: AuthenticatedAiCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmergencyFundRoute: AuthenticatedEmergencyFundRoute,
  AuthenticatedFinancialHealthRoute: AuthenticatedFinancialHealthRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedInsuranceRoute: AuthenticatedInsuranceRoute,
  AuthenticatedNetWorthRoute: AuthenticatedNetWorthRoute,
  AuthenticatedPeerBenchmarkRoute: AuthenticatedPeerBenchmarkRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedRetirementRoute: AuthenticatedRetirementRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSimulatorRoute: AuthenticatedSimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
