/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RetirementRouteImport } from './routes/retirement'
import { Route as PrinciplesRouteImport } from './routes/principles'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as EmergencyFundRouteImport } from './routes/emergency-fund'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirementRoute = RetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesRoute = PrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyFundRoute = EmergencyFundRouteImport.update({
  id: '/emergency-fund',
  path: '/emergency-fund',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/emergency-fund': typeof EmergencyFundRoute
  '/goals': typeof GoalsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/knowledge': typeof KnowledgeRoute
  '/net-worth': typeof NetWorthRoute
  '/principles': typeof PrinciplesRoute
  '/retirement': typeof RetirementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/emergency-fund': typeof EmergencyFundRoute
  '/goals': typeof GoalsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/knowledge': typeof KnowledgeRoute
  '/net-worth': typeof NetWorthRoute
  '/principles': typeof PrinciplesRoute
  '/retirement': typeof RetirementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/emergency-fund': typeof EmergencyFundRoute
  '/goals': typeof GoalsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/knowledge': typeof KnowledgeRoute
  '/net-worth': typeof NetWorthRoute
  '/principles': typeof PrinciplesRoute
  '/retirement': typeof RetirementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/emergency-fund'
    | '/goals'
    | '/how-it-works'
    | '/insurance'
    | '/knowledge'
    | '/net-worth'
    | '/principles'
    | '/retirement'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/emergency-fund'
    | '/goals'
    | '/how-it-works'
    | '/insurance'
    | '/knowledge'
    | '/net-worth'
    | '/principles'
    | '/retirement'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/emergency-fund'
    | '/goals'
    | '/how-it-works'
    | '/insurance'
    | '/knowledge'
    | '/net-worth'
    | '/principles'
    | '/retirement'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  EmergencyFundRoute: typeof EmergencyFundRoute
  GoalsRoute: typeof GoalsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InsuranceRoute: typeof InsuranceRoute
  KnowledgeRoute: typeof KnowledgeRoute
  NetWorthRoute: typeof NetWorthRoute
  PrinciplesRoute: typeof PrinciplesRoute
  RetirementRoute: typeof RetirementRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirement': {
      id: '/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof RetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles': {
      id: '/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof PrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-fund': {
      id: '/emergency-fund'
      path: '/emergency-fund'
      fullPath: '/emergency-fund'
      preLoaderRoute: typeof EmergencyFundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  EmergencyFundRoute: EmergencyFundRoute,
  GoalsRoute: GoalsRoute,
  HowItWorksRoute: HowItWorksRoute,
  InsuranceRoute: InsuranceRoute,
  KnowledgeRoute: KnowledgeRoute,
  NetWorthRoute: NetWorthRoute,
  PrinciplesRoute: PrinciplesRoute,
  RetirementRoute: RetirementRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
