// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type BrowserRuntimeEnv = {
  SUPABASE_URL?: string;
  SUPABASE_PUBLISHABLE_KEY?: string;
};

function normalizeSupabaseUrl(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  if (!trimmed) return undefined;
  return /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed.replace(/^\/+/, '')}`;
}

function getBrowserRuntimeEnv(): BrowserRuntimeEnv | undefined {
  if (typeof window === 'undefined') return undefined;
  return (window as unknown as { __NITIVITT_ENV?: BrowserRuntimeEnv }).__NITIVITT_ENV;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Resolution order (platform-agnostic):
  //   1. window.__NITIVITT_ENV — injected at SSR from runtime env (Cloudflare Workers, etc.)
  //   2. import.meta.env.VITE_*  — Vite build-time replacement only when no runtime injection exists
  //   3. process.env.*           — Node/SSR fallback
  const runtime = getBrowserRuntimeEnv();
  const hasRuntimeInjection = typeof window !== 'undefined' && runtime !== undefined;

  const SUPABASE_URL = normalizeSupabaseUrl(
    runtime?.SUPABASE_URL ||
      (!hasRuntimeInjection ? import.meta.env.VITE_SUPABASE_URL : undefined) ||
      (typeof process !== "undefined" ? process.env.SUPABASE_URL : undefined),
  );
  const SUPABASE_PUBLISHABLE_KEY =
    runtime?.SUPABASE_PUBLISHABLE_KEY ||
    (!hasRuntimeInjection ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY : undefined) ||
    (typeof process !== "undefined" ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set them in the deployment environment.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

